CREATE TABLE [stage].[INSTANCEServerProperties]
(
[datetimeid] [bigint] NULL,
[projectHashId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BuildCLRVersion] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductLevel] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductBuildType] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Instance] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[InstanceDefaultLogPath] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[local_tcp_port] [int] NULL,
[IsHadrEnabled] [int] NULL,
[IsClustered] [int] NULL,
[ProductVersion] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductUpdateLevel] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IsFullTextInstalled] [int] NULL,
[FilestreamConfiguredLevel] [int] NULL,
[ComputerNamePhysicalNetBIOS] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductUpdateReference] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProcessID] [int] NULL,
[IsIntegratedSecurityOnly] [int] NULL,
[IsXTPSupported] [int] NULL,
[Collation] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Edition] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductMajorVersion] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductBuild] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FQDN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MachineName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HadrManagerStatus] [int] NULL,
[InstanceDefaultDataPath] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServerName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProductMinorVersion] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
