CREATE TABLE [stage].[INSTANCEQueryPlansCPUBounds]
(
[datetimeid] [bigint] NULL,
[projectHashId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[rowHash] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[creation_time] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_clr_time] [int] NULL,
[min_ideal_grant_kb] [int] NULL,
[max_rows] [int] NULL,
[query_plan_hash] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_rows] [int] NULL,
[last_execution_time] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_grant_kb] [int] NULL,
[min_used_threads] [int] NULL,
[total_num_page_server_reads] [int] NULL,
[total_ideal_grant_kb] [int] NULL,
[last_spills] [int] NULL,
[statement_end_offset] [int] NULL,
[min_logical_reads] [int] NULL,
[min_elapsed_time] [int] NULL,
[min_num_page_server_reads] [int] NULL,
[last_dop] [int] NULL,
[max_elapsed_time] [int] NULL,
[text] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_used_grant_kb] [int] NULL,
[sql_handle] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_rows] [int] NULL,
[total_worker_time] [int] NULL,
[last_num_physical_reads] [int] NULL,
[max_page_server_reads] [int] NULL,
[max_logical_writes] [int] NULL,
[min_logical_writes] [int] NULL,
[last_used_threads] [int] NULL,
[last_used_grant_kb] [int] NULL,
[total_columnstore_segment_skips] [int] NULL,
[total_physical_reads] [int] NULL,
[max_num_page_server_reads] [int] NULL,
[max_physical_reads] [int] NULL,
[max_used_grant_kb] [int] NULL,
[min_page_server_reads] [int] NULL,
[min_worker_time] [int] NULL,
[max_num_physical_reads] [int] NULL,
[last_num_page_server_reads] [int] NULL,
[FQDN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_grant_kb] [int] NULL,
[execution_count] [int] NULL,
[min_physical_reads] [int] NULL,
[min_dop] [int] NULL,
[query_plan] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[min_reserved_threads] [int] NULL,
[total_clr_time] [int] NULL,
[min_columnstore_segment_reads] [int] NULL,
[last_elapsed_time] [int] NULL,
[max_dop] [int] NULL,
[last_columnstore_segment_reads] [int] NULL,
[max_columnstore_segment_skips] [int] NULL,
[total_num_physical_reads] [int] NULL,
[total_spills] [int] NULL,
[min_num_physical_reads] [int] NULL,
[statement_start_offset] [int] NULL,
[total_columnstore_segment_reads] [int] NULL,
[max_worker_time] [int] NULL,
[min_used_grant_kb] [int] NULL,
[max_ideal_grant_kb] [int] NULL,
[max_reserved_threads] [int] NULL,
[max_spills] [int] NULL,
[query_hash] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[total_logical_writes] [int] NULL,
[total_logical_reads] [int] NULL,
[max_clr_time] [int] NULL,
[max_grant_kb] [int] NULL,
[plan_handle] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[min_rows] [int] NULL,
[total_dop] [int] NULL,
[total_page_server_reads] [int] NULL,
[last_logical_writes] [int] NULL,
[total_elapsed_time] [int] NULL,
[statement_context_id] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[max_logical_reads] [int] NULL,
[total_used_threads] [int] NULL,
[last_worker_time] [int] NULL,
[min_clr_time] [int] NULL,
[max_used_threads] [int] NULL,
[total_reserved_threads] [int] NULL,
[statement_sql_handle] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[last_ideal_grant_kb] [int] NULL,
[last_logical_reads] [int] NULL,
[min_grant_kb] [int] NULL,
[max_columnstore_segment_reads] [int] NULL,
[last_columnstore_segment_skips] [int] NULL,
[last_reserved_threads] [int] NULL,
[last_physical_reads] [int] NULL,
[min_spills] [int] NULL,
[last_page_server_reads] [int] NULL,
[ServerName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[min_columnstore_segment_skips] [int] NULL,
[plan_generation_num] [int] NULL
) ON [PRIMARY]
GO
