CREATE TABLE [stage].[DATABASESystemFilesInfo]
(
[datetimeid] [bigint] NULL,
[projectHashId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[physical_name] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_media_read_only] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[data_space_id] [int] NULL,
[is_percent_growth] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drop_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type] [int] NULL,
[backup_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[differential_base_time] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_read_only] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[type_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state] [int] NULL,
[read_only_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[create_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[file_guid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_sparse] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_name_reserved] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[differential_base_guid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[max_size] [int] NULL,
[read_write_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FQDN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[size] [int] NULL,
[redo_target_fork_guid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[differential_base_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[redo_target_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[redo_start_lsn] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServerName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[file_id] [int] NULL,
[name] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[redo_start_fork_guid] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[growth] [int] NULL
) ON [PRIMARY]
GO
