CREATE TABLE [stage].[INSTANCEDatabaseProperties]
(
[datetimeid] [bigint] NULL,
[projectHashId] [nvarchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[target_recovery_time_in_seconds] [int] NULL,
[is_published] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[local_tcp_port] [int] NULL,
[RecoveryModel] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_auto_close_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[delayed_durability_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBCompatibilityLevel] [int] NULL,
[encryption_state] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[state_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[containment_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_distributor] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[key_length] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_memory_optimized_elevate_to_snapshot_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PageVerifyOption] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[replica_id] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_auto_shrink_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_encrypted] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DatabaseOwner] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[group_database_id] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_auto_create_stats_incremental_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_parameterization_forced] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_read_committed_snapshot_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[key_algorithm] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[percent_complete] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_auto_update_stats_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FQDN] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogUsedInPercent] [int] NULL,
[is_auto_update_stats_async_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ServerName] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[snapshot_isolation_state_desc] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_cdc_enabled] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogReuseWaitDescription] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogSizeMB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LogUsedMB] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_auto_create_stats_on] [nvarchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
